// Throwaway rendering only. Content comes from the same Jekyll _posts as the published blog.
const variants = ['A', 'B', 'C', 'D', 'E'];
const names = ['The sleeve', 'Liner notes', 'The catalogue', 'Listening room', 'The quarterly'];
const ideas = ['A record-sleeve feature with a tracklist of recent stories.', 'An intimate, text-led journal with generous reading space.', 'A searchable archive organised like a collector’s catalogue.', 'An evening reading layout with a quiet, dark canvas.', 'An art-directed magazine spread with oversized serif typography.'];
const categories = {'all':'All articles','vinyl-collecting':'Vinyl collecting','vinyl-care':'Vinyl care','music-discovery':'Music discovery','app-tips':'App tips'};
const params = new URLSearchParams(location.search);
let variant = variants.includes(params.get('variant')) ? params.get('variant') : 'A';
let category = 'all';
let query = '';
let posts = [];
let article = params.get('article');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])).replace(/[—–]/g, ',');
const image = (p, cls='') => `<img class="photo ${cls}" src="${esc(p.image)}" alt="Illustration accompanying ${esc(p.title)}" loading="lazy">`;
const meta = p => `<p class="meta">${esc(categories[p.category] || 'Vinyl collecting')} <span>·</span> ${esc(p.reading_time || 7)} min read</p>`;
const link = p => `?variant=${variant}&article=${encodeURIComponent(p.id)}`;
const title = (p, level=2) => `<h${level}><a href="${link(p)}" data-article="${esc(p.id)}">${esc(p.title)}</a></h${level}>`;
const ruleTitle = text => `<div class="section-title"><h2>${text}</h2><span>The Vinyl Journal</span></div>`;
const row = (p, i) => `<article class="story-row"><span class="row-number">${String(i+1).padStart(2,'0')}</span><div>${meta(p)}${title(p)}<p class="description">${esc(p.description)}</p></div><a tabindex="-1" aria-hidden="true" href="${link(p)}" data-article="${esc(p.id)}">${image(p)}</a></article>`;
const tile = p => `<article class="story-tile"><a tabindex="-1" aria-hidden="true" href="${link(p)}" data-article="${esc(p.id)}">${image(p)}</a>${meta(p)}${title(p)}<p class="description">${esc(p.description)}</p></article>`;
function filters() { return `<div class="filters"><div class="categories" role="group" aria-label="Filter articles">${Object.entries(categories).map(([key,name])=>`<button data-category="${key}" aria-pressed="${category===key}">${name}</button>`).join('')}</div><label class="search"><span>Search</span><input type="search" placeholder="Find a story" aria-label="Search articles" value="${esc(query)}"></label></div>`; }
function filtered() { return posts.filter(p=>(category==='all'||p.category===category)&&`${p.title} ${p.description}`.toLowerCase().includes(query.toLowerCase())); }
function results() { const list=filtered(); return `<p class="result-count" aria-live="polite">${list.length} articles${query ? ` matching “${esc(query)}”`:''}</p><div class="result-list">${list.length ? list.slice(0,18).map(row).join(''):'<h2>No articles found</h2><p>Try another search or choose All articles.</p>'}</div>`; }
function VariantA(p) { return `<div class="masthead"><h1>The Vinyl Journal<span class="dot">.</span></h1><p>For the records you keep.<br> And the stories behind them.</p></div><section class="sleeve-feature"><div class="sleeve-image">${image(p[0])}<span class="sleeve-stamp">MY VINYL+<br>THE JOURNAL</span></div><div class="feature-copy">${meta(p[0])}${title(p[0])}<p>${esc(p[0].description)}</p><a class="read-link" href="${link(p[0])}" data-article="${p[0].id}">Read the story <span>↗</span></a><div class="sleeve-bottom">Notes on collecting, care and discovery.<span>33⅓ RPM</span></div></div></section>${filters()}<section id="results">${ruleTitle('Fresh from the crate')}<div class="a-latest">${p.slice(1,5).map(row).join('')}</div></section>`; }
function VariantB(p) { return `<div class="notes-layout"><aside class="notes-sidebar"><div class="record-mark" aria-hidden="true"><span>MY<br>VINYL+</span></div><h1>Liner<br><em>notes.</em></h1><p>The Vinyl Journal</p><p class="sidebar-description">A little more knowledge.<br>A lot more listening.</p><a href="#browse">Browse the journal ↓</a></aside><div class="notes-main"><section class="notes-lead">${meta(p[0])}${title(p[0])}<p class="intro">${esc(p[0].paragraphs[0])}</p><a class="read-link" href="${link(p[0])}" data-article="${p[0].id}">Continue reading ↗</a>${image(p[0])}</section><div id="browse">${filters()}</div><section id="results">${ruleTitle('More liner notes')}${p.slice(1,6).map(row).join('')}</section></div></div>`; }
function VariantC(p) { return `<section class="catalogue-heading"><div><h1>The record<br><em>of collecting.</em></h1><p>The Vinyl Journal, by My Vinyl+</p></div><p class="catalogue-note">Practical knowledge for your collection.<br>Care, collecting, discovery and app guides.<br><strong>${posts.length} articles to dig through.</strong></p></section>${filters()}<section id="results"><div class="catalogue-labels"><span>From the journal</span><span>Title / subject</span><span>Reading time</span></div>${p.slice(0,12).map((post,i)=>`<article class="catalogue-row"><a class="catalogue-art" aria-hidden="true" tabindex="-1" href="${link(post)}" data-article="${post.id}">${image(post)}</a><div>${meta(post)}${title(post)}<p class="description">${esc(post.description)}</p></div><a class="catalogue-time" href="${link(post)}" data-article="${post.id}" aria-label="Read ${esc(post.title)}">${post.reading_time || 7} min <span>↗</span></a></article>`).join('')}</section>`; }
function VariantD(p) { return `<section class="room-title"><h1>The listening room<span>.</span></h1><p>Turn the record over.<br> Stay a little longer.</p></section><section class="room-feature"><div>${meta(p[0])}${title(p[0])}<p class="intro">${esc(p[0].description)}</p><a class="read-link" href="${link(p[0])}" data-article="${p[0].id}">Settle in and read ↗</a><p class="room-credit">The Vinyl Journal / My Vinyl+</p></div><div class="room-photo">${image(p[0])}<span>On care & collecting</span></div></section>${filters()}<section id="results">${ruleTitle('Next in the queue')}<div class="room-queue">${p.slice(1,5).map(tile).join('')}</div></section>`; }
function VariantE(p) { return `<div class="quarterly-top"><span>My Vinyl+ presents</span><span>A journal for record people</span></div><h1 class="quarterly-title">Wax &<em> words.</em></h1><section class="quarterly-feature"><div class="quarterly-margin"><span>The Vinyl Journal</span><p>Collect well.<br>Listen closely.</p></div><div class="quarterly-photo">${image(p[0])}</div><div class="quarterly-copy">${meta(p[0])}${title(p[0])}<p>${esc(p[0].description)}</p><a class="read-link" href="${link(p[0])}" data-article="${p[0].id}">Read the feature ↗</a></div></section>${filters()}<section id="results">${ruleTitle('In this journal')}<div class="quarterly-stories">${p.slice(1,4).map(tile).join('')}</div></section>`; }
function reader(p) { return `<a class="back" href="?variant=${variant}" data-back>← Back to the journal</a><article class="reader"><header>${meta(p)}<h1>${esc(p.title)}</h1><p class="reader-deck">${esc(p.description)}</p><p class="byline">By ${esc(p.author || 'Matteo Comisso')} · ${p.id.slice(8,10)} ${new Date(p.id.slice(0,10)+'T12:00:00').toLocaleString('en-GB',{month:'long',year:'numeric'})}</p></header>${image(p)}<div class="reader-body"><p class="preview-note">Reading preview · Opening extracts from the published article</p>${p.paragraphs.map(x=>`<p>${esc(x)}</p>`).join('')}<a class="read-link" href="${esc(p.url)}">Read the complete published article ↗</a></div></article>`; }
function updateURL() { const url=new URL(location.href); url.searchParams.set('variant',variant); article?url.searchParams.set('article',article):url.searchParams.delete('article'); history.replaceState({},'',url); }
function render() { document.body.dataset.variant=variant; const p=posts; const selected=p.find(x=>x.id===article); document.querySelector('#main').innerHTML=selected?reader(selected):({A:VariantA,B:VariantB,C:VariantC,D:VariantD,E:VariantE}[variant])(p); document.querySelector('#variant').value=variant; document.querySelector('#count').textContent=`${variants.indexOf(variant)+1}/5`; document.querySelector('#home').href=`?variant=${variant}`; document.title=`${names[variants.indexOf(variant)]} | My Vinyl+ prototype`; updateURL(); if(!selected&&(query||category!=='all')) document.querySelector('#results').innerHTML=results(); console.info('Prototype state',{variant,name:names[variants.indexOf(variant)],designQuestion:ideas[variants.indexOf(variant)],category,query,article,articleCount:posts.length}); }
function cycle(step) { variant=variants[(variants.indexOf(variant)+step+5)%5]; render(); document.querySelector(".preview-page").scrollTo(0,0); }
document.querySelector('#next').onclick=()=>cycle(1);
document.querySelector('#previous').onclick=()=>cycle(-1);
document.querySelector('#variant').onchange=e=>{variant=e.target.value;render();document.querySelector(".preview-page").scrollTo(0,0);};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cycle(e.key==='ArrowRight'?1:-1);}});
document.addEventListener('click',e=>{const story=e.target.closest('[data-article]');const back=e.target.closest('[data-back]');const cat=e.target.closest('[data-category]');if(story||back){e.preventDefault();article=story?.dataset.article||null;render();document.querySelector(".preview-page").scrollTo(0,0);document.querySelector('#main').focus();}if(cat){category=cat.dataset.category;render();}});
document.addEventListener('input',e=>{if(e.target.matches('.search input')){query=e.target.value;document.querySelector('#results').innerHTML=results();console.info('Prototype filter state',{variant,category,query,results:filtered().length});}});
// Local preview only: the switcher cannot appear on a production host.
document.querySelector('.switcher').hidden=!['localhost','127.0.0.1'].includes(location.hostname);
fetch('/prototype-data.json').then(r=>r.json()).then(data=>{posts=data;render();});
